### ISSUE TITLE
请问如何部署到vps上呢

### ISSUE THREAD

**Issue by njzhenghao** [Phuker/Searchit#1]
我想将这个项目部署到自己的vps上，然后就供几个人访问，请问如何配置呢，谢谢

**Comment by Phuker** [comment]
参阅readme.md主要配置一节。最好安装curl扩展。
主要配置**/proxy/proxy_conf.php**和**/search.php**
前者中的`'proxy'=>true,'proxyHost'=>'127.0.0.1',    'proxyPort'=>8080,` 部分控制了服务器端访问百度和谷歌的方式。海外VPS无需通过代理访问Google（设置'proxy'为false），国内的请自备代理。
后者的

```
$googleurl='./proxy/proxy.php?engine=google&q='; // local proxy
$baiduurl='./proxy/proxy.php?engine=baidu&q='; 
```

控制是否通过服务器反向代理访问百度和谷歌（框架的地址）。由于Google的iframe策略，$googleurl保持不变，为了美化显示效果$baiduurl也可以保持不变。

**Comment by njzhenghao** [comment]
你好，麻烦你了，我修改了直连，因为是洛杉矶的vps，但是google页面没有东西
百度的有，s.hatebug.com，麻烦帮看一下，谢谢

**search.php修改的内容**
![search.php](https://ooo.0o0.ooo/2016/09/19/57df72bbb6d0b.png)

**proxy_conf.php修改的内容（不过是不是与这个没有关系，没走代理啊）**
![proxy_conf.php](https://ooo.0o0.ooo/2016/09/19/57df7339d09ab.png)

**Comment by Phuker** [comment]
不好意思刚刚看到回复XD
你的情况下 $googleurl $baiduurl 不能这样设置，因为：
此选项控制浏览器访问百度和谷歌的方式，如果浏览器在国内则无法正常访问谷歌。
由于Google的frame同源策略（x-frame-options:SAMEORIGIN），Google即使能连接，也会无法正常显示。

一般来说国外VPS国内使用的话，百度部分无所谓，谷歌应该使用/proxy/proxy.php才能绕过frame同源策略。

**Comment by lianyis** [comment]
右侧frame内的google搜索点击下一页或者选其它数字会跳转到一个新窗口，并直接使用google搜索，请问怎么处理一下？

**Comment by Phuker** [comment]
你好，在我的实际使用过程中几乎从来没有用过翻页，所以并没有做反向代理proxy.php部分的翻页功能，而是通过在头部添加
`<base href="https://www.google.com/" target="_blank" />`，
点击之后直接在新窗口中打开Google。如果你经常要用到翻页，建议可以在config.php 里面找到Google的URL，把页码部分（num=20）改大一点。一般来说再加上选好关键词搜索很少用到翻页。

**Comment by jamboo2017** [comment]
请问提示如下错误怎么处理？谢谢
SSL certificate: /volume2/web/baigoogledu/proxy/cert/baidu.com.crt

**Comment by Phuker** [comment]
应该同时还有一个 Curl error: xxx 的报错，把那个贴上来吧
